services:
  - type: web
    name: wedding-planner-server
    env: node
    buildCommand: |
      echo "Starting build process..."
      cd server
      echo "Installing server dependencies..."
      npm install
      echo "Building server..."
      npm run build:clean
      echo "Build complete. Checking dist folder contents:"
      ls -la dist/
      echo "Checking if server.js exists:"
      test -f dist/server.js && echo "server.js exists" || echo "server.js NOT found"
      echo "Running build verification..."
      node verify-build.js
    startCommand: cd server && node start.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 5000
