services:
  - type: web
    name: wedding-planner-server
    env: node
    buildCommand: |
      npm install
      cd server && npm install
      cd server && npm run build:clean
    startCommand: cd server && node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 5000
