services:
  - type: web
    name: wedding-planner-server
    env: node
    buildCommand: |
      npm install
      npm run install-all
      npm run build:server
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 5000
